<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Sql</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\eng\versions\Sql.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\tooling\BlueTusk.Sql.Tool\BlueTusk.Sql.Tool.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Sql.SourceGeneration\BlueTusk.Sql.SourceGeneration.csproj" />
  </ItemGroup>
</Project>
