<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Edge</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\eng\versions\Edge.props" />
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\BlueTusk.Data\BlueTusk.Data.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Edge.Sqlite\BlueTusk.Edge.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Edge.Server\BlueTusk.Edge.Server.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Edge.Http\BlueTusk.Edge.Http.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Edge.AspNetCore\BlueTusk.Edge.AspNetCore.csproj" />
  </ItemGroup>
</Project>
