FROM mcr.microsoft.com/dotnet/sdk:10.0.302@sha256:72dd743782f2ae7e5476fd64f6a460045e3998dc862218b80e6944cba79a01b0 AS build
ARG PROJECT_FAMILY
WORKDIR /source
COPY Directory.Build.props Directory.Packages.props README.md ./
COPY applications/ applications/
RUN dotnet restore "applications/src/${PROJECT_FAMILY}/BlueTusk.${PROJECT_FAMILY}.Worker/BlueTusk.${PROJECT_FAMILY}.Worker.csproj" \
    --source https://api.nuget.org/v3/index.json
RUN dotnet publish "applications/src/${PROJECT_FAMILY}/BlueTusk.${PROJECT_FAMILY}.Worker/BlueTusk.${PROJECT_FAMILY}.Worker.csproj" \
    --configuration Release --no-restore --output /app /p:UseAppHost=false && \
    cp "/app/BlueTusk.${PROJECT_FAMILY}.Worker.dll" /app/BlueTusk.Application.Worker.dll && \
    cp "/app/BlueTusk.${PROJECT_FAMILY}.Worker.deps.json" /app/BlueTusk.Application.Worker.deps.json && \
    cp "/app/BlueTusk.${PROJECT_FAMILY}.Worker.runtimeconfig.json" /app/BlueTusk.Application.Worker.runtimeconfig.json

FROM mcr.microsoft.com/dotnet/runtime:10.0.11-noble-chiseled@sha256:faeea3edbaf9b13cc84dad62a5072cc96a888272087e3aa461268f612bdee702
ARG PROJECT_FAMILY
ENV DOTNET_EnableDiagnostics=0 PROJECT_FAMILY=${PROJECT_FAMILY}
WORKDIR /app
COPY --from=build --chown=1654:1654 /app ./
USER 1654:1654
ENTRYPOINT ["dotnet", "BlueTusk.Application.Worker.dll"]
