FROM node:24.19.0-alpine3.23@sha256:244cc2b53f46f9e876304391d17682b0ddae9ac33491f4857e25e35a36ba7995 AS build
ARG WEB_DIRECTORY
ARG WEB_OUTPUT=dist
WORKDIR /source
COPY "applications/web/${WEB_DIRECTORY}/package.json" "applications/web/${WEB_DIRECTORY}/package-lock.json" ./
RUN npm ci --ignore-scripts --no-audit --no-fund
COPY "applications/web/${WEB_DIRECTORY}/" ./
RUN npm run build && mkdir -p /output && cp -R "${WEB_OUTPUT}/." /output/

FROM nginxinc/nginx-unprivileged:1.30.3-alpine3.23@sha256:b3f2436575bd5be7386518084d842dac414ab4962712afa31e99e0942a56e3b2
COPY applications/containers/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build --chown=101:101 /output/ /usr/share/nginx/html/
USER 101:101
EXPOSE 8080
