FROM node:24.15.0-alpine3.23@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f AS build
ARG WEB_DIRECTORY
ARG WEB_OUTPUT=dist
WORKDIR /source
COPY "applications/web/${WEB_DIRECTORY}/package.json" "applications/web/${WEB_DIRECTORY}/package-lock.json" ./
RUN npm ci --ignore-scripts --no-audit --no-fund
COPY "applications/web/${WEB_DIRECTORY}/" ./
RUN npm run build && mkdir -p /output && cp -R "${WEB_OUTPUT}/." /output/

FROM nginxinc/nginx-unprivileged:1.29.4-alpine3.23@sha256:a6c4f61f456b85b8fdf7ec7ab28cc3e299440e6fb4a9dea520e5fd8fd440025e
COPY applications/containers/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build --chown=101:101 /output/ /usr/share/nginx/html/
USER 101:101
EXPOSE 8080
