<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Search</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\eng\versions\Search.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.Search\BlueTusk.Search.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Data\BlueTusk.Data.csproj" />
  </ItemGroup>
</Project>
