// <auto-generated />
using System;
using BlueTusk.ServiceTopology.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueTusk.ServiceTopology.Infrastructure.Migrations
{
    [DbContext(typeof(TopologyDbContext))]
    [Migration("20260807211255_InitialTopology")]
    partial class InitialTopology
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("topology")
                .HasPropertyGraphs("[{\"name\":\"service_topology_graph\",\"schema\":\"topology\",\"elementTables\":[{\"alias\":\"services\",\"kind\":\"Vertex\",\"table\":\"services\",\"schema\":\"topology\",\"keyColumns\":[\"Id\"],\"labels\":[{\"name\":\"service\",\"properties\":[{\"expression\":\"Id\",\"name\":\"Id\",\"isColumn\":true},{\"expression\":\"Name\",\"name\":\"Name\",\"isColumn\":true},{\"expression\":\"Health\",\"name\":\"Health\",\"isColumn\":true}]}],\"source\":null,\"destination\":null},{\"alias\":\"dependencies\",\"kind\":\"Edge\",\"table\":\"dependencies\",\"schema\":\"topology\",\"keyColumns\":[\"Id\"],\"labels\":[{\"name\":\"depends_on\",\"properties\":[]}],\"source\":{\"vertexTableAlias\":\"services\",\"edgeKeyColumns\":[\"SourceId\"],\"vertexKeyColumns\":[\"Id\"]},\"destination\":{\"vertexTableAlias\":\"services\",\"edgeKeyColumns\":[\"DestinationId\"],\"vertexKeyColumns\":[\"Id\"]}}]}]")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BlueTusk.ServiceTopology.Domain.ServiceDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceId", "DestinationId")
                        .IsUnique();

                    b.ToTable("dependencies", "topology");
                });

            modelBuilder.Entity("BlueTusk.ServiceTopology.Domain.ServiceNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("services", "topology");
                });

            modelBuilder.Entity("BlueTusk.ServiceTopology.Domain.TopologyIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("incidents", "topology");
                });
#pragma warning restore 612, 618
        }
    }
}
