import { CapabilityRecord, EvidenceRecord, ProductStatus, SearchRecord } from './models';

export const REPOSITORY_URL = 'https://github.com/jphgardner/BlueTusk';
export const sourceUrl = (path: string, anchor = '') =>
  `${REPOSITORY_URL}/blob/main/${path}${anchor ? `#${anchor}` : ''}`;

export const PRODUCT_STATUSES: readonly ProductStatus[] = [
  {
    id: 'provider',
    name: 'ADO.NET Provider',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet RC',
    gateState: 'RC package and install checks passed',
    evidence: ['Clean package install', 'Npgsql comparison', 'ADO.NET compatibility'],
    limitations: ['Stable 1.1 waits for the final release test programme'],
  },
  {
    id: 'ef-core',
    name: 'EF Core',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet RC',
    gateState: 'RC package and install checks passed',
    evidence: ['1,987 official tests passed', 'PostgreSQL 15–19 tested'],
    limitations: ['124 tests are skipped by the official upstream EF Core suite'],
  },
  {
    id: 'streams',
    name: 'Streams',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet RC',
    gateState: '72-hour stable test pending',
    evidence: ['Safe initial load', 'Recoverable replay', 'Exact-candidate verifier'],
    limitations: ['Required archived 72-hour endurance run is pending'],
  },
  {
    id: 'sync',
    name: 'Sync',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet RC',
    gateState: '24-hour stable test pending',
    evidence: ['Four destination recovery models', 'Repair, quarantine, and rebuild'],
    limitations: ['The exact candidate long-running test report must be archived'],
  },
  {
    id: 'live',
    name: 'Live',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet + npm RC',
    gateState: 'RC package and install checks passed',
    evidence: ['PostgreSQL 15–19 replay tests', 'Security and load tests'],
    limitations: ['Stable release still needs long-running and user acceptance tests'],
  },
  {
    id: 'control-plane',
    name: 'Control Plane',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet RC',
    gateState: 'Stable operational test pending',
    evidence: ['Versioned agent API', 'PostgreSQL audit and repair'],
    limitations: ['Stable release follows the tested dependency and long-running test sequence'],
  },
  {
    id: 'continuous-graph',
    name: 'Continuous Graph',
    version: '1.1.0-rc.1',
    stage: 'gate-passed',
    packageState: 'Public NuGet RC',
    gateState: 'PostgreSQL 19 GA and 24-hour test pending',
    evidence: ['Three safe update modes', 'Full-query repair fallback', 'Metrics for each mode'],
    limitations: ['Stable support waits for PostgreSQL 19 GA and the exact 24-hour test'],
  },
] as const;

export const EVIDENCE: readonly EvidenceRecord[] = [
  {
    id: 'rc-publication',
    subsystem: 'Platform',
    kind: 'release',
    status: 'passed',
    value: '65 / 65',
    label: 'Public 1.1 RC packages',
    detail:
      'All 62 NuGet packages and three npm clients are public at 1.1.0-rc.1 and resolved in clean consumers.',
    asOf: '2026-08-29',
    sourcePath: 'docs/releases/1.1.0-rc.1.md',
  },
  {
    id: 'rc-family-workflows',
    subsystem: 'Platform',
    kind: 'release',
    status: 'passed',
    value: '6 / 6',
    label: 'All six product releases passed',
    detail:
      'Provider, Streams, Sync, Live, Control Plane, and Continuous Graph were built from the same source commit.',
    asOf: '2026-08-29',
    sourcePath: 'docs/releases/1.1.0-rc.1.md',
  },
  {
    id: 'rc-consumer-smoke',
    subsystem: 'Platform',
    kind: 'tests',
    status: 'passed',
    value: '0 errors',
    label: 'Clean application install',
    detail:
      'A new .NET 10 application built with all six product families, and all three npm clients installed with no reported vulnerabilities.',
    asOf: '2026-08-29',
    sourcePath: 'docs/releases/1.1.0-rc.1.md',
  },
  {
    id: 'pg-matrix',
    subsystem: 'Provider',
    kind: 'compatibility',
    status: 'passed',
    value: '15–19',
    label: 'PostgreSQL matrix',
    detail:
      'Provider, replication, compatibility, and feature tests run against five PostgreSQL generations.',
    asOf: '2026-08-04',
    sourcePath: 'docs/contributing/testing.md',
  },
  {
    id: 'pg19-final',
    subsystem: 'Platform',
    kind: 'tests',
    status: 'passed',
    value: '3,289 / 0',
    label: 'PostgreSQL 19 full matrix',
    detail:
      '3,289 passed with zero failures across 45 test assemblies; 158 environment-specific cases were not executed.',
    asOf: '2026-08-04',
    sourcePath: 'docs/v1-release-readiness.md',
  },
  {
    id: 'ado-compat',
    subsystem: 'Provider',
    kind: 'compatibility',
    status: 'passed',
    value: '11 / 11',
    label: 'ADO.NET live compatibility',
    detail:
      'Functions, procedures, IN/OUT/INOUT rows, Dapper, schema APIs, DI and health checks passed.',
    asOf: '2026-08-04',
    sourcePath: 'docs/ado-net/compatibility.md',
  },
  {
    id: 'ef-suite',
    subsystem: 'EF Core',
    kind: 'tests',
    status: 'passed',
    value: '1,987 / 2,111',
    label: 'Official EF Core tests',
    detail: '1,987 passed; 124 are skipped by the official upstream EF Core suite.',
    asOf: '2026-08-04',
    sourcePath: 'docs/ef-core/specification-tests.md',
  },
  {
    id: 'fuzzing',
    subsystem: 'Platform',
    kind: 'security',
    status: 'pending',
    value: 'Review open',
    label: 'Parser-finding review',
    detail:
      'Nine parser test targets are ready. The latest run passed six and stopped safely on three; those results need independent review and a rerun on the exact release candidate.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/fuzz-finding-handoff.md',
  },
  {
    id: 'test-credential-boundary',
    subsystem: 'Platform',
    kind: 'security',
    status: 'passed',
    value: '22 scoped',
    label: 'Intentional test credentials',
    detail:
      'All 22 test credentials are recorded and restricted to localhost or disposable test systems. Any unknown value or external host stops the check.',
    asOf: '2026-08-04',
    sourcePath: 'docs/security.md',
  },
  {
    id: 'secret-scanner-triage',
    subsystem: 'Platform',
    kind: 'security',
    status: 'pending',
    value: '6 pending',
    label: 'External scanner disposition',
    detail:
      'The pull request warnings match known test values, but an independent reviewer must still confirm that they are false positives.',
    asOf: '2026-08-04',
    sourcePath: 'docs/security.md',
  },
  {
    id: 'api-budget',
    subsystem: 'Platform',
    kind: 'compatibility',
    status: 'passed',
    value: '13,056',
    label: 'Public APIs checked',
    detail:
      '13,056 API signatures are tracked across six products. An unreviewed change fails the build.',
    asOf: '2026-08-29',
    sourcePath: 'docs/api-compatibility.md',
  },
  {
    id: 'allocations',
    subsystem: 'Platform',
    kind: 'performance',
    status: 'passed',
    value: '46',
    label: 'Memory-use checks',
    detail: 'Automated memory limits cover commands, COPY, replication, EF, Live, Sync, and graph.',
    asOf: '2026-08-29',
    sourcePath: 'docs/architecture/allocation-discipline.md',
  },
  {
    id: 'supply-chain',
    subsystem: 'Platform',
    kind: 'security',
    status: 'passed',
    value: '60 hashes',
    label: 'Package identity and contents',
    detail:
      '31 Provider packages and 29 symbol packages matched the expected source commit, file hashes, and software inventories.',
    asOf: '2026-08-04',
    sourcePath: 'docs/release-process.md',
  },
  {
    id: 'canonical-package-set',
    subsystem: 'Platform',
    kind: 'release',
    status: 'passed',
    value: '65 public',
    label: 'All product packages verified',
    detail:
      'Every 1.1.0-rc.1 package is public and passed exact-version NuGet/npm installation tests.',
    asOf: '2026-08-29',
    sourcePath: 'docs/releases/1.1.0-rc.1.md',
  },
  {
    id: 'vulnerabilities',
    subsystem: 'Platform',
    kind: 'security',
    status: 'passed',
    value: '0 matched',
    label: 'Known dependency vulnerabilities',
    detail:
      'No known NuGet security advisory matched a direct or indirect dependency in the checked build.',
    asOf: '2026-08-04',
    sourcePath: 'docs/security.md',
  },
  {
    id: 'website-delivery',
    subsystem: 'Website',
    kind: 'performance',
    status: 'passed',
    value: '< 140 KiB',
    label: 'Initial Brotli budget',
    detail:
      'The Angular production build enforces raw and compressed startup, lazy-chunk and complete-distribution budgets with hashed assets and no source maps.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/website-production.md',
  },
  {
    id: 'website-field-vitals',
    subsystem: 'Website',
    kind: 'release',
    status: 'pending',
    value: 'Pilot pending',
    label: 'Field Core Web Vitals',
    detail:
      'The public host still needs 100 field samples over 28 days with p75 LCP ≤2,500 ms, INP ≤200 ms and CLS ≤0.1.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/approval-evidence.md',
  },
  {
    id: 'streams-endurance',
    subsystem: 'Streams',
    kind: 'release',
    status: 'pending',
    value: '72h pending',
    label: 'Streams 72-hour test',
    detail:
      'The test and automatic result checker are ready, but the required successful 72-hour run is not complete.',
    asOf: '2026-08-04',
    sourcePath: 'docs/streams/release-endurance.md',
  },
  {
    id: 'sync-endurance',
    subsystem: 'Sync',
    kind: 'release',
    status: 'pending',
    value: '24h pending',
    label: 'Sync 24-hour test',
    detail: 'Stable Sync waits until the exact candidate completes and passes its 24-hour test.',
    asOf: '2026-08-04',
    sourcePath: 'docs/sync/release-endurance.md',
  },
  {
    id: 'endurance-disturbances',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: '14 pending',
    label: 'Planned failure-and-recovery tests',
    detail:
      'The long-running Streams and Sync tests must each recover from seven planned failures and save the results for review.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/endurance-disturbance-evidence.md',
  },
  {
    id: 'live-preview',
    subsystem: 'Live',
    kind: 'release',
    status: 'passed',
    value: 'Code-ready',
    label: 'Live V1 implementation',
    detail:
      'Replay, permissions, transports, clients, security, load, stored formats, and package tests are implemented.',
    asOf: '2026-08-04',
    sourcePath: 'docs/live/README.md',
  },
  {
    id: 'graph-pg19',
    subsystem: 'Graph',
    kind: 'compatibility',
    status: 'guarded',
    value: 'GA pending',
    label: 'PostgreSQL 19 graph queries',
    detail:
      'Beta 3 is tested from a fixed container image. Stable support waits for the final PostgreSQL 19 release.',
    asOf: '2026-08-04',
    sourcePath: 'docs/postgresql19-programme.md',
  },
  {
    id: 'operational-approvals',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: '10 required',
    label: 'Production operations approval',
    detail:
      'Ten measured checks need external evidence and ordered approval; written assurances without measurements do not pass.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/approval-evidence.md',
  },
  {
    id: 'independent-review',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: 'Pending',
    label: 'Final independent review',
    detail:
      'The exact release candidate still needs application trials, backup and restore checks, a rollback rehearsal, and maintainer approval.',
    asOf: '2026-08-04',
    sourcePath: 'docs/release-review-handoff.md',
  },
] as const;

export const EXTENSION_CAPABILITIES: readonly CapabilityRecord[] = [
  {
    surface: 'ADO.NET + EF',
    feature: 'citext',
    workload: 'Case-insensitive text',
    postgres: '15–19',
    state: 'supported',
    notes: 'Scalar and array mappings with EF translation.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'pgvector',
    workload: 'Vector search',
    postgres: '15–19',
    state: 'supported',
    notes: 'Vector, half-vector, sparse-vector, and distance operators.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'hstore',
    workload: 'Key/value data',
    postgres: '15–19',
    state: 'supported',
    notes: 'Key/value mapping works in ADO.NET and EF Core, including arrays.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'ltree',
    workload: 'Hierarchies',
    postgres: '15–19',
    state: 'supported',
    notes: 'Typed .NET values for paths and PostgreSQL hierarchy queries.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'pg_trgm',
    workload: 'Fuzzy search',
    postgres: '15–19',
    state: 'supported',
    notes: 'Fuzzy text matching and similarity queries in EF Core.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET',
    feature: 'pg_durable',
    workload: 'Durable workflows',
    postgres: '17 / 0.2.5 gate',
    state: 'preview',
    notes: 'Evaluation only. The upstream preview is not approved for production use.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'PostGIS',
    workload: 'Spatial',
    postgres: '18 gate',
    state: 'supported',
    notes: 'PostGIS 3.6 spatial values and queries tested end to end.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'TimescaleDB',
    workload: 'Time series',
    postgres: '17 gate',
    state: 'supported',
    notes: 'TimescaleDB 2.29 queries, including compiled EF Core queries.',
    sourcePath: 'docs/extensions/README.md',
  },
] as const;

export const SITE_SEARCH: readonly SearchRecord[] = [
  {
    title: 'Platform architecture',
    description: 'Choose the smallest BlueTusk layer for your workload.',
    route: '/platform',
    group: 'Platform',
    keywords: 'architecture dependencies security observability',
  },
  {
    title: 'ADO.NET Provider',
    description: 'Connections, pooling, types, COPY, notifications, and replication.',
    route: '/provider',
    group: 'Products',
    keywords: 'authentication tls scram oauth gssapi multi-host',
  },
  {
    title: 'EF Core',
    description: 'LINQ, PostgreSQL mappings, migrations, and database-first workflows.',
    route: '/ef-core',
    group: 'Products',
    keywords: 'linq json array range schema database first',
  },
  {
    title: 'Real Time',
    description: 'Capture committed changes, deliver them, and operate the pipeline.',
    route: '/real-time',
    group: 'Products',
    keywords: 'cdc snapshot relay replay checkpoint destinations',
  },
  {
    title: 'Extensions',
    description: 'PostGIS, pgvector, TimescaleDB, pg_durable, citext, hstore, ltree, and pg_trgm.',
    route: '/extensions',
    group: 'Products',
    keywords: 'spatial vector timeseries types',
  },
  {
    title: 'Graph',
    description: 'Capability-guarded SQL/PGQ and incremental graph results.',
    route: '/graph',
    group: 'Products',
    keywords: 'property graph fraud network reactive',
  },
  {
    title: 'Engineering evidence',
    description: 'Verified results, guarded capabilities, and work still open.',
    route: '/evidence',
    group: 'Trust',
    keywords: '1987 2111 allocation 72h 24h',
  },
  {
    title: 'Documentation',
    description: 'Task-oriented guides generated from the repository documentation.',
    route: '/documentation',
    group: 'Learn',
    keywords: 'guides getting started api',
  },
  {
    title: 'Community',
    description: 'Build, test, contribute, and report issues.',
    route: '/community',
    group: 'Contribute',
    keywords: 'github issue security contributing',
  },
] as const;
