import { CapabilityRecord, EvidenceRecord, ProductStatus, SearchRecord } from './models';

export const REPOSITORY_URL = 'https://github.com/jphgardner/BlueTusk';
export const sourceUrl = (path: string, anchor = '') =>
  `${REPOSITORY_URL}/blob/main/${path}${anchor ? `#${anchor}` : ''}`;

export const PRODUCT_STATUSES: readonly ProductStatus[] = [
  {
    id: 'provider',
    name: 'ADO.NET Provider',
    version: '0.3.0 preview',
    stage: 'gate-passed',
    packageState: 'Verified candidate only',
    gateState: 'V1 code-ready',
    evidence: ['PostgreSQL 15–19 matrix', 'ADO.NET compatibility', 'Bounded parser fuzzing'],
    limitations: ['Stable publication and external production validation remain gated'],
  },
  {
    id: 'ef-core',
    name: 'EF Core',
    version: '0.3.0 preview',
    stage: 'gate-passed',
    packageState: 'Verified candidate only',
    gateState: 'V1 code-ready',
    evidence: ['1,987 official specification passes', 'PostgreSQL 15–19 matrix'],
    limitations: ['124 upstream tests retain their upstream skip declarations'],
  },
  {
    id: 'streams',
    name: 'Streams',
    version: '0.1 preview',
    stage: 'pending',
    packageState: 'Candidate only',
    gateState: '72-hour evidence pending',
    evidence: ['Snapshot bootstrap', 'Durable relay', 'Exact-candidate verifier'],
    limitations: ['Required archived 72-hour endurance run is pending'],
  },
  {
    id: 'sync',
    name: 'Sync',
    version: 'Preview train',
    stage: 'pending',
    packageState: 'Not publishable',
    gateState: '24-hour evidence pending',
    evidence: ['Four destination contracts', 'Reconciliation, quarantine and rebuild'],
    limitations: ['The exact candidate endurance report must be archived'],
  },
  {
    id: 'live',
    name: 'Live',
    version: '0.1 preview',
    stage: 'gate-passed',
    packageState: 'Verified candidate only',
    gateState: 'V1 code-ready',
    evidence: ['PostgreSQL 15–19 replay matrix', 'Security and load gates'],
    limitations: ['Stable publication follows the dependency-ordered release chain'],
  },
  {
    id: 'control-plane',
    name: 'Control Plane',
    version: '0.1 preview',
    stage: 'pending',
    packageState: 'Candidate only',
    gateState: 'Dependency evidence pending',
    evidence: ['Versioned agent contract', 'PostgreSQL audit and reconciliation'],
    limitations: ['Publication waits for Streams, Sync and Live dependencies'],
  },
  {
    id: 'continuous-graph',
    name: 'Continuous Graph',
    version: '0.1 preview',
    stage: 'gate-passed',
    packageState: 'Verified preview candidate',
    gateState: 'V1 preview code-ready',
    evidence: ['Fraud and network samples', 'Checkpointed graph updates'],
    limitations: ['Publication waits for the dependency-ordered release chain'],
  },
] as const;

export const EVIDENCE: readonly EvidenceRecord[] = [
  {
    id: 'pg-matrix',
    subsystem: 'Provider',
    kind: 'compatibility',
    status: 'passed',
    value: '15–19',
    label: 'PostgreSQL matrix',
    detail:
      'Provider, replication, compatibility, and feature gates run against five PostgreSQL generations.',
    asOf: '2026-08-04',
    sourcePath: 'docs/contributing/testing.md',
  },
  {
    id: 'pg19-final',
    subsystem: 'Platform',
    kind: 'tests',
    status: 'passed',
    value: '3,289 / 0',
    label: 'PostgreSQL 19 full matrix',
    detail:
      '3,289 passed with zero failures across 45 test assemblies; 158 environment-specific cases were not executed.',
    asOf: '2026-08-04',
    sourcePath: 'docs/v1-release-readiness.md',
  },
  {
    id: 'ado-compat',
    subsystem: 'Provider',
    kind: 'compatibility',
    status: 'passed',
    value: '11 / 11',
    label: 'ADO.NET live compatibility',
    detail:
      'Functions, procedures, IN/OUT/INOUT rows, Dapper, schema APIs, DI and health checks passed.',
    asOf: '2026-08-04',
    sourcePath: 'docs/ado-net/compatibility.md',
  },
  {
    id: 'ef-suite',
    subsystem: 'EF Core',
    kind: 'tests',
    status: 'passed',
    value: '1,987 / 2,111',
    label: 'Official EF cases',
    detail: '1,987 pass; 124 retain upstream EF skip declarations.',
    asOf: '2026-08-04',
    sourcePath: 'docs/ef-core/specification-tests.md',
  },
  {
    id: 'fuzzing',
    subsystem: 'Platform',
    kind: 'security',
    status: 'pending',
    value: 'Review open',
    label: 'Parser-finding review',
    detail:
      'Nine bounded targets and deterministic corpus coverage are implemented; the latest run passed six targets and failed closed on three pending independent review and an exact-candidate rerun.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/fuzz-finding-handoff.md',
  },
  {
    id: 'test-credential-boundary',
    subsystem: 'Platform',
    kind: 'security',
    status: 'passed',
    value: '22 scoped',
    label: 'Intentional test credentials',
    detail:
      'Every literal is fingerprinted, counted and confined to localhost or disposable Compose/Kerberos infrastructure; unknown or external-host use fails closed.',
    asOf: '2026-08-04',
    sourcePath: 'docs/security.md',
  },
  {
    id: 'secret-scanner-triage',
    subsystem: 'Platform',
    kind: 'security',
    status: 'pending',
    value: '6 pending',
    label: 'External scanner disposition',
    detail:
      'The live PR findings match inventoried test values, but an independent reviewer must still record the external false-positive disposition.',
    asOf: '2026-08-04',
    sourcePath: 'docs/security.md',
  },
  {
    id: 'api-budget',
    subsystem: 'Platform',
    kind: 'compatibility',
    status: 'passed',
    value: '12,975',
    label: 'Public API budget',
    detail:
      'Exact signatures are budgeted across six product families and unreviewed growth fails CI.',
    asOf: '2026-08-04',
    sourcePath: 'docs/api-compatibility.md',
  },
  {
    id: 'allocations',
    subsystem: 'Platform',
    kind: 'performance',
    status: 'passed',
    value: '37',
    label: 'Allocation budgets',
    detail: 'Machine-checked command, COPY, replication, EF, Live, Sync and graph budgets.',
    asOf: '2026-08-04',
    sourcePath: 'docs/architecture/allocation-discipline.md',
  },
  {
    id: 'supply-chain',
    subsystem: 'Platform',
    kind: 'security',
    status: 'passed',
    value: '60 hashes',
    label: 'Candidate provenance smoke',
    detail:
      '32 Provider packages and 30 symbol packages matched commit-bound hashes, CycloneDX and SPDX records.',
    asOf: '2026-08-04',
    sourcePath: 'docs/release-process.md',
  },
  {
    id: 'canonical-package-set',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: 'Build pending',
    label: 'Six-family package evidence',
    detail:
      'The exact inventory, content, SHA-256, CycloneDX, SPDX and provenance verifier is implemented; the retained manual candidate build is still required.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/package-evidence.md',
  },
  {
    id: 'vulnerabilities',
    subsystem: 'Platform',
    kind: 'security',
    status: 'passed',
    value: '0 matched',
    label: 'Dependency advisory audit',
    detail:
      'No direct or transitive NuGet advisory matched the solution at the V1 hardening snapshot.',
    asOf: '2026-08-04',
    sourcePath: 'docs/security.md',
  },
  {
    id: 'website-delivery',
    subsystem: 'Website',
    kind: 'performance',
    status: 'passed',
    value: '< 140 KiB',
    label: 'Initial Brotli budget',
    detail:
      'The Angular production build enforces raw and compressed startup, lazy-chunk and complete-distribution budgets with hashed assets and no source maps.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/website-production.md',
  },
  {
    id: 'website-field-vitals',
    subsystem: 'Website',
    kind: 'release',
    status: 'pending',
    value: 'Pilot pending',
    label: 'Field Core Web Vitals',
    detail:
      'The public host still needs 100 field samples over 28 days with p75 LCP ≤2,500 ms, INP ≤200 ms and CLS ≤0.1.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/approval-evidence.md',
  },
  {
    id: 'streams-endurance',
    subsystem: 'Streams',
    kind: 'release',
    status: 'pending',
    value: '72h pending',
    label: 'Streams endurance archive',
    detail:
      'The exact-candidate harness and verifier exist; the required successful archived run is not complete.',
    asOf: '2026-08-04',
    sourcePath: 'docs/streams/release-endurance.md',
  },
  {
    id: 'sync-endurance',
    subsystem: 'Sync',
    kind: 'release',
    status: 'pending',
    value: '24h pending',
    label: 'Sync endurance archive',
    detail: 'The release train remains non-publishable until the exact candidate report passes.',
    asOf: '2026-08-04',
    sourcePath: 'docs/sync/release-endurance.md',
  },
  {
    id: 'endurance-disturbances',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: '14 pending',
    label: 'Operational disturbance recoveries',
    detail:
      'Both exact endurance windows must each contain seven passed, content-addressed production disturbance recoveries backed by 28 unique injection/recovery summaries.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/endurance-disturbance-evidence.md',
  },
  {
    id: 'live-preview',
    subsystem: 'Live',
    kind: 'release',
    status: 'passed',
    value: 'Code-ready',
    label: 'Live V1 implementation',
    detail:
      'Replay, authorization, transports, clients, security, load, format and package gates are implemented.',
    asOf: '2026-08-04',
    sourcePath: 'docs/live/README.md',
  },
  {
    id: 'graph-pg19',
    subsystem: 'Graph',
    kind: 'compatibility',
    status: 'guarded',
    value: 'GA pending',
    label: 'PostgreSQL 19 SQL/PGQ',
    detail:
      'Beta 2 is digest-pinned and capability-guarded; stable support waits for the GA programme.',
    asOf: '2026-08-04',
    sourcePath: 'docs/postgresql19-programme.md',
  },
  {
    id: 'operational-approvals',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: '10 required',
    label: 'Measured operational acceptance',
    detail:
      'Gate-specific schemas reject narrative-only or stale approvals and enforce final review/sign-off ordering; measured external records remain outstanding.',
    asOf: '2026-08-04',
    sourcePath: 'docs/operations/approval-evidence.md',
  },
  {
    id: 'independent-review',
    subsystem: 'Platform',
    kind: 'release',
    status: 'pending',
    value: 'Pending',
    label: 'Independent release review',
    detail:
      'Pilots, backup/restore, rollback rehearsal and maintainer sign-off must bind to the exact candidate.',
    asOf: '2026-08-04',
    sourcePath: 'docs/release-review-handoff.md',
  },
] as const;

export const EXTENSION_CAPABILITIES: readonly CapabilityRecord[] = [
  {
    surface: 'ADO.NET + EF',
    feature: 'citext',
    workload: 'Case-insensitive text',
    postgres: '15–19',
    state: 'preview',
    notes: 'Scalar and array mappings with EF translation.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'pgvector',
    workload: 'Vector search',
    postgres: '15–19',
    state: 'preview',
    notes: 'Vector, half-vector, sparse-vector, and distance operators.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'hstore',
    workload: 'Key/value data',
    postgres: '15–19',
    state: 'preview',
    notes: 'Runtime catalogue composition includes array support.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'ltree',
    workload: 'Hierarchies',
    postgres: '15–19',
    state: 'preview',
    notes: 'Distinct ltree, lquery, and ltxtquery CLR values.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'pg_trgm',
    workload: 'Fuzzy search',
    postgres: '15–19',
    state: 'preview',
    notes: 'Similarity and word-distance translation.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET',
    feature: 'pg_durable',
    workload: 'Durable workflows',
    postgres: '17 / 0.2.5 gate',
    state: 'preview',
    notes: 'Parameterized workflow lifecycle, signals, cancellation, and metrics.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'PostGIS',
    workload: 'Spatial',
    postgres: '18 gate',
    state: 'preview',
    notes: 'PostGIS 3.6 catalogue, round-trip, and query gate.',
    sourcePath: 'docs/extensions/README.md',
  },
  {
    surface: 'ADO.NET + EF',
    feature: 'TimescaleDB',
    workload: 'Time series',
    postgres: '17 gate',
    state: 'preview',
    notes: 'TimescaleDB 2.29 query and compiled-query gate.',
    sourcePath: 'docs/extensions/README.md',
  },
] as const;

export const SITE_SEARCH: readonly SearchRecord[] = [
  {
    title: 'Platform architecture',
    description: 'Layers, ownership, journeys, and maturity.',
    route: '/platform',
    group: 'Platform',
    keywords: 'architecture dependencies security observability',
  },
  {
    title: 'ADO.NET Provider',
    description: 'Connections, pooling, types, COPY, notifications, and replication.',
    route: '/provider',
    group: 'Products',
    keywords: 'authentication tls scram oauth gssapi multi-host',
  },
  {
    title: 'EF Core',
    description: 'Queries, mappings, migrations, scaffolding, and graph.',
    route: '/ef-core',
    group: 'Products',
    keywords: 'linq json array range schema database first',
  },
  {
    title: 'Real Time',
    description: 'Streams, Sync, Live, and Control Plane.',
    route: '/real-time',
    group: 'Products',
    keywords: 'cdc snapshot relay replay checkpoint destinations',
  },
  {
    title: 'Extensions',
    description: 'PostGIS, pgvector, TimescaleDB, pg_durable, citext, hstore, ltree, and pg_trgm.',
    route: '/extensions',
    group: 'Products',
    keywords: 'spatial vector timeseries types',
  },
  {
    title: 'Graph',
    description: 'PostgreSQL 19 SQL/PGQ and Continuous Graph.',
    route: '/graph',
    group: 'Products',
    keywords: 'property graph fraud network reactive',
  },
  {
    title: 'Engineering evidence',
    description: 'Compatibility, tests, security, performance, and release gates.',
    route: '/evidence',
    group: 'Trust',
    keywords: '1987 2111 allocation 72h 24h',
  },
  {
    title: 'Documentation',
    description: 'Build-time synchronized technical guides.',
    route: '/documentation',
    group: 'Learn',
    keywords: 'guides getting started api',
  },
  {
    title: 'Community',
    description: 'Build, test, contribute, and report issues.',
    route: '/community',
    group: 'Contribute',
    keywords: 'github issue security contributing',
  },
] as const;
