<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Workflows</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\eng\versions\Workflows.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.Workflows\BlueTusk.Workflows.csproj" />
  </ItemGroup>
</Project>
