apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bluetusk.fullname" . }}-configuration
  labels: {{- include "bluetusk.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ ternary "Staging" "Production" (eq .Values.environment "rc") | quote }}
  Authentication__Authority: {{ .Values.authentication.authority | quote }}
  Authentication__ClientId: {{ .Values.authentication.clientId | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.observability.otlpEndpoint | quote }}
  OTEL_SERVICE_NAMESPACE: bluetusk-applications
