{{- range $component := list "api" "worker" "ui" "migration" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bluetusk.fullname" $ }}-{{ $component }}
  labels:
    {{- include "bluetusk.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
automountServiceAccountToken: false
---
{{- end }}
