[libdefaults]
    default_realm = BLUETUSK.TEST
    dns_lookup_kdc = false
    dns_lookup_realm = false
    dns_canonicalize_hostname = false
    rdns = false
    udp_preference_limit = 1

[realms]
    BLUETUSK.TEST = {
        kdc = gss18:88
    }

[domain_realm]
    .bluetusk.test = BLUETUSK.TEST
    bluetusk.test = BLUETUSK.TEST
