local all all trust
host all bluetusk_gss_test 0.0.0.0/0 gss include_realm=0 krb_realm=BLUETUSK.TEST
host all bluetusk_gss_test ::0/0 gss include_realm=0 krb_realm=BLUETUSK.TEST
host all all 0.0.0.0/0 scram-sha-256
host all all ::0/0 scram-sha-256
