<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Sync</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="..\..\eng\versions\Sync.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.Streams.Testing\BlueTusk.Streams.Testing.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Sync.Redis\BlueTusk.Sync.Redis.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Sync.Testing\BlueTusk.Sync.Testing.csproj" />
  </ItemGroup>
</Project>
