<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.ControlPlane\BlueTusk.ControlPlane.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Data\BlueTusk.Data.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Replication\BlueTusk.Replication.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Replication.PgOutput\BlueTusk.Replication.PgOutput.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Streams\BlueTusk.Streams.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Streams.Storage.PostgreSql\BlueTusk.Streams.Storage.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Streams.Storage.Redis\BlueTusk.Streams.Storage.Redis.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Streams.Testing\BlueTusk.Streams.Testing.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Sync\BlueTusk.Sync.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Sync.DependencyInjection\BlueTusk.Sync.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
