// <auto-generated />
using System;
using BlueTusk.FraudInvestigation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueTusk.FraudInvestigation.Infrastructure.Migrations
{
    [DbContext(typeof(FraudDbContext))]
    partial class FraudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fraud")
                .HasPropertyGraphs("[{\"name\":\"fraud_graph\",\"schema\":\"fraud\",\"elementTables\":[{\"alias\":\"accounts\",\"kind\":\"Vertex\",\"table\":\"accounts\",\"schema\":\"fraud\",\"keyColumns\":[\"Id\"],\"labels\":[{\"name\":\"account\",\"properties\":[{\"expression\":\"Id\",\"name\":\"Id\",\"isColumn\":true},{\"expression\":\"DisplayName\",\"name\":\"DisplayName\",\"isColumn\":true}]}],\"source\":null,\"destination\":null},{\"alias\":\"transfers\",\"kind\":\"Edge\",\"table\":\"transfers\",\"schema\":\"fraud\",\"keyColumns\":[\"Id\"],\"labels\":[{\"name\":\"transfer\",\"properties\":[{\"expression\":\"Id\",\"name\":\"Id\",\"isColumn\":true},{\"expression\":\"Amount\",\"name\":\"Amount\",\"isColumn\":true},{\"expression\":\"Currency\",\"name\":\"Currency\",\"isColumn\":true}]}],\"source\":{\"vertexTableAlias\":\"accounts\",\"edgeKeyColumns\":[\"SourceId\"],\"vertexKeyColumns\":[\"Id\"]},\"destination\":{\"vertexTableAlias\":\"accounts\",\"edgeKeyColumns\":[\"DestinationId\"],\"vertexKeyColumns\":[\"Id\"]}}]}]")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BlueTusk.FraudInvestigation.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("accounts", "fraud");
                });

            modelBuilder.Entity("BlueTusk.FraudInvestigation.Domain.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinimumAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("alert_rules", "fraud");
                });

            modelBuilder.Entity("BlueTusk.FraudInvestigation.Domain.InvestigationCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assignee")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("investigation_cases", "fraud");
                });

            modelBuilder.Entity("BlueTusk.FraudInvestigation.Domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RecordedAt");

                    b.ToTable("transfers", "fraud");
                });

            modelBuilder.Entity("BlueTusk.FraudInvestigation.Infrastructure.FraudEvidenceAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseId", "RecordedAt");

                    b.ToTable("evidence_audit", "fraud");
                });
#pragma warning restore 612, 618
        }
    }
}
