<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Events</BlueTuskProductFamily>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <SelfContained>true</SelfContained>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\eng\versions\Events.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.Events\BlueTusk.Events.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Events.Streams\BlueTusk.Events.Streams.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Streams.Testing\BlueTusk.Streams.Testing.csproj" />
  </ItemGroup>
</Project>
