using BlueTusk.Data;
using BlueTusk.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Xunit.Sdk;

namespace BlueTusk.EntityFrameworkCore.Tests;

public sealed class CrudIntegrationTests
{
    [Fact]
    public async Task EF_Core_executes_CRUD_against_PostgreSQL()
    {
        var connectionString = GetConnectionString();
        await RecreateTableAsync(connectionString);

        try
        {
            var generatedId = 0;
            await using (var context = CreateContext(connectionString))
            {
                var blog = new Blog { Name = "BlueTusk", IsActive = true };
                context.Blogs.Add(blog);
                Assert.Equal(1, await context.SaveChangesAsync());
                Assert.True(blog.Id > 0);
                generatedId = blog.Id;
            }

            await using (var context = CreateContext(connectionString))
            {
                var blog = await context.Blogs.SingleAsync(candidate => candidate.Id == generatedId);
                Assert.Equal("BlueTusk", blog.Name);
                Assert.True(blog.IsActive);

                blog.Name = "BlueTusk EF";
                Assert.Equal(1, await context.SaveChangesAsync());
            }

            await using (var context = CreateContext(connectionString))
            {
                var blog = await context.Blogs.SingleAsync();
                Assert.Equal("BlueTusk EF", blog.Name);

                context.Blogs.Remove(blog);
                Assert.Equal(1, await context.SaveChangesAsync());
                Assert.Equal(0, await context.Blogs.CountAsync());
            }

            await using (var context = CreateContext(connectionString))
            {
                await using var transaction = await context.Database.BeginTransactionAsync();
                context.Blogs.Add(new Blog { Name = "Rolled back", IsActive = false });
                Assert.Equal(1, await context.SaveChangesAsync());
                await transaction.RollbackAsync();
            }

            await using (var context = CreateContext(connectionString))
            {
                Assert.Equal(0, await context.Blogs.CountAsync());
            }
        }
        finally
        {
            await ExecuteNonQueryAsync(connectionString, "DROP TABLE IF EXISTS \"ef_crud_blogs\"");
        }
    }

    private static BlogContext CreateContext(string connectionString)
    {
        var options = new DbContextOptionsBuilder<BlogContext>()
            .UseBlueTusk(connectionString)
            .Options;
        return new BlogContext(options);
    }

    private static async Task RecreateTableAsync(string connectionString)
    {
        await ExecuteNonQueryAsync(connectionString, "DROP TABLE IF EXISTS \"ef_crud_blogs\"");
        await ExecuteNonQueryAsync(
            connectionString,
            "CREATE TABLE \"ef_crud_blogs\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Name\" text NOT NULL, \"IsActive\" boolean NOT NULL)");
    }

    private static async Task ExecuteNonQueryAsync(string connectionString, string sql)
    {
        await using var connection = new BlueTuskConnection(connectionString);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        _ = await command.ExecuteNonQueryAsync(CancellationToken.None);
    }

    private static string GetConnectionString()
    {
        var connectionString = Environment.GetEnvironmentVariable("BLUETUSK_TEST_CONNECTION_STRING");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            throw SkipException.ForSkip("BLUETUSK_TEST_CONNECTION_STRING is not configured.");
        }

        return new BlueTuskConnectionStringBuilder(connectionString)
        {
            SslMode = BlueTuskSslMode.Disable,
            ChannelBinding = BlueTuskChannelBindingMode.Disable,
        }.ConnectionString;
    }

    private sealed class BlogContext(DbContextOptions<BlogContext> options) : DbContext(options)
    {
        public DbSet<Blog> Blogs => Set<Blog>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
            => ConfigureBlog(modelBuilder.Entity<Blog>());

        private static void ConfigureBlog(EntityTypeBuilder<Blog> blog)
        {
            blog.ToTable("ef_crud_blogs");
            blog.HasKey(entity => entity.Id);
            blog.Property(entity => entity.Id).ValueGeneratedOnAdd();
            blog.Property(entity => entity.Name).IsRequired();
        }
    }

    private sealed class Blog
    {
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public bool IsActive { get; set; }
    }
}
