using BlueTusk.Client;
using BlueTusk.Data;
using BlueTusk.EntityFrameworkCore.Design.Internal;
using BlueTusk.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Scaffolding;
using Microsoft.Extensions.DependencyInjection;
using Xunit.Sdk;

namespace BlueTusk.EntityFrameworkCore.Tests;

#pragma warning disable EF1001

public sealed class GeneratedColumnMigrationsTests
{
    private const string Offline = "Host=localhost;Database=unused;Username=unused;Password=unused";
    private const string Schema = "generated_tests";
    private const string Table = "generated_records";

    [Fact]
    public void Identity_generated_column_and_comment_SQL_is_typed_guarded_and_alterable()
    {
        using var initial = Create<InitialContext>(Offline);
        using var byDefault = Create<ByDefaultContext>(Offline);
        using var altered = Create<AlteredStoredContext>(Offline);
        using var virtualContext = Create<VirtualAlteredContext>(Offline);
        using var ordinary = Create<OrdinaryContext>(Offline);
        var initialModel = initial.GetService<IDesignTimeModel>().Model;
        var differ = initial.GetService<IMigrationsModelDiffer>();
        var generator = initial.GetService<IMigrationsSqlGenerator>();
        var createSql = string.Concat(generator.Generate(
                differ.GetDifferences(null, initialModel.GetRelationalModel()), initialModel)
            .Select(command => command.CommandText));
        Assert.Contains("\"id\" bigint NOT NULL GENERATED ALWAYS AS IDENTITY", createSql,
            StringComparison.Ordinal);
        Assert.Contains("\"stored_value\" integer GENERATED ALWAYS AS (\"base_value\" * 2) STORED",
            createSql, StringComparison.Ordinal);
        Assert.Contains("COMMENT ON TABLE \"generated_tests\".\"generated_records\" IS 'Initial table'",
            createSql, StringComparison.Ordinal);
        Assert.Contains("COMMENT ON COLUMN \"generated_tests\".\"generated_records\".\"id\" " +
                        "IS 'Always identity'", createSql, StringComparison.Ordinal);
        Assert.Contains("COMMENT ON COLUMN \"generated_tests\".\"generated_records\".\"stored_value\" " +
                        "IS 'Stored result'", createSql, StringComparison.Ordinal);

        var byDefaultModel = byDefault.GetService<IDesignTimeModel>().Model;
        var identitySql = string.Concat(generator.Generate(
                differ.GetDifferences(initialModel.GetRelationalModel(), byDefaultModel.GetRelationalModel()),
                byDefaultModel)
            .Select(command => command.CommandText));
        Assert.Contains("ALTER COLUMN \"id\" SET GENERATED BY DEFAULT", identitySql,
            StringComparison.Ordinal);
        Assert.Contains("COMMENT ON TABLE \"generated_tests\".\"generated_records\" IS 'Updated table'",
            identitySql, StringComparison.Ordinal);
        Assert.Contains("COMMENT ON COLUMN \"generated_tests\".\"generated_records\".\"id\" IS NULL",
            identitySql, StringComparison.Ordinal);

        var alteredModel = altered.GetService<IDesignTimeModel>().Model;
        var expressionSql = string.Concat(generator.Generate(
                differ.GetDifferences(byDefaultModel.GetRelationalModel(), alteredModel.GetRelationalModel()),
                alteredModel)
            .Select(command => command.CommandText));
        Assert.Contains("server_version_num')::integer < 170000", expressionSql, StringComparison.Ordinal);
        Assert.Contains("ALTER COLUMN \"stored_value\" SET EXPRESSION AS (\"base_value\" * 3)",
            expressionSql, StringComparison.Ordinal);

        var virtualModel = virtualContext.GetService<IDesignTimeModel>().Model;
        var virtualCommands = generator.Generate(
            differ.GetDifferences(alteredModel.GetRelationalModel(), virtualModel.GetRelationalModel()),
            virtualModel);
        var virtualSql = string.Concat(virtualCommands.Select(command => command.CommandText));
        Assert.Contains("server_version_num')::integer < 180000", virtualSql, StringComparison.Ordinal);
        Assert.Contains("\"virtual_value\" integer GENERATED ALWAYS AS (\"base_value\" + 1) VIRTUAL",
            virtualSql, StringComparison.Ordinal);
        Assert.Contains("COMMENT ON COLUMN \"generated_tests\".\"generated_records\".\"virtual_value\" " +
                        "IS 'Virtual result'", virtualSql, StringComparison.Ordinal);

        var ordinaryModel = ordinary.GetService<IDesignTimeModel>().Model;
        var dropExpressionSql = string.Concat(generator.Generate(
                differ.GetDifferences(alteredModel.GetRelationalModel(), ordinaryModel.GetRelationalModel()),
                ordinaryModel)
            .Select(command => command.CommandText));
        Assert.Contains("ALTER COLUMN \"stored_value\" DROP EXPRESSION", dropExpressionSql,
            StringComparison.Ordinal);
    }

    [Fact]
    public async Task Identity_generated_columns_and_comments_round_trip_across_PostgreSQL()
    {
        var cs = ConnectionString();
        await Cleanup(cs);
        try
        {
            using var initial = Create<InitialContext>(cs);
            var initialModel = initial.GetService<IDesignTimeModel>().Model;
            await Apply(initial, null, initialModel, cs);
            await Execute(cs,
                "INSERT INTO generated_tests.generated_records (base_value) VALUES (4)");
            Assert.Equal(8, await Scalar(cs,
                "SELECT stored_value FROM generated_tests.generated_records"));
            await Assert.ThrowsAsync<BlueTuskException>(() => Execute(cs,
                "INSERT INTO generated_tests.generated_records (id, base_value) VALUES (100, 5)"));

            var database = new BlueTuskDatabaseModelFactory().Create(
                cs,
                new DatabaseModelFactoryOptions([], [Schema]));
            var table = Assert.Single(database.Tables);
            Assert.Equal("Initial table", table.Comment);
            var id = table.Columns.Single(column => column.Name == "id");
            Assert.Equal((int)BlueTuskIdentityGeneration.Always,
                id[BlueTuskValueGenerationAnnotations.IdentityGeneration]);
            Assert.Equal("Always identity", id.Comment);
            var stored = table.Columns.Single(column => column.Name == "stored_value");
            Assert.True(stored.IsStored);
            Assert.Equal("(base_value * 2)", stored.ComputedColumnSql);
            Assert.Equal("Stored result", stored.Comment);

            using (var provider = DesignServices())
            {
                var scaffolded = provider.GetRequiredService<IReverseEngineerScaffolder>().ScaffoldModel(
                    cs,
                    new DatabaseModelFactoryOptions([], [Schema]),
                    new ModelReverseEngineerOptions(),
                    new ModelCodeGenerationOptions
                    {
                        ContextName = "GeneratedScaffoldContext",
                        ConnectionString = cs,
                        ContextNamespace = "GeneratedModels",
                        ModelNamespace = "GeneratedModels",
                        RootNamespace = "GeneratedModels",
                        Language = "C#",
                        ProjectDir = AppContext.BaseDirectory,
                        UseNullableReferenceTypes = true,
                    });
                Assert.Contains("UseIdentityColumn(BlueTuskIdentityGeneration.Always)",
                    scaffolded.ContextFile.Code, StringComparison.Ordinal);
                Assert.Contains("HasComputedColumnSql(\"(base_value * 2)\"",
                    scaffolded.ContextFile.Code, StringComparison.Ordinal);
                Assert.Contains("HasComment(\"Initial table\")", scaffolded.ContextFile.Code,
                    StringComparison.Ordinal);
            }

            using var byDefault = Create<ByDefaultContext>(cs);
            var byDefaultModel = byDefault.GetService<IDesignTimeModel>().Model;
            await Apply(byDefault, initialModel, byDefaultModel, cs);
            await Execute(cs,
                "INSERT INTO generated_tests.generated_records (id, base_value) VALUES (100, 5)");
            Assert.Equal("Updated table", await Scalar(cs,
                "SELECT pg_catalog.obj_description('generated_tests.generated_records'::regclass)"));
            Assert.Same(DBNull.Value, await Scalar(cs,
                "SELECT pg_catalog.col_description('generated_tests.generated_records'::regclass, 1)"));

            var serverVersion = Convert.ToInt32(await Scalar(cs, "SHOW server_version_num"),
                System.Globalization.CultureInfo.InvariantCulture);
            IModel currentModel = byDefaultModel;
            if (serverVersion >= 170000)
            {
                using var altered = Create<AlteredStoredContext>(cs);
                var alteredModel = altered.GetService<IDesignTimeModel>().Model;
                await Apply(altered, byDefaultModel, alteredModel, cs);
                currentModel = alteredModel;
                Assert.Equal(15, await Scalar(cs,
                    "SELECT stored_value FROM generated_tests.generated_records WHERE id = 100"));
            }
            else
            {
                using var altered = Create<AlteredStoredContext>(cs);
                var commands = Commands(altered, byDefaultModel,
                    altered.GetService<IDesignTimeModel>().Model);
                var exception = await Assert.ThrowsAsync<BlueTuskException>(() =>
                    Execute(cs, commands[0].CommandText));
                Assert.Contains("require PostgreSQL 17 or later", exception.Message,
                    StringComparison.Ordinal);
            }

            DbContext virtualContext = serverVersion >= 170000
                ? Create<VirtualAlteredContext>(cs)
                : Create<VirtualInitialContext>(cs);
            await using (virtualContext)
            {
                var virtualModel = virtualContext.GetService<IDesignTimeModel>().Model;
                if (serverVersion >= 180000)
                {
                    await Apply(virtualContext, currentModel, virtualModel, cs);
                    currentModel = virtualModel;
                    Assert.Equal(6, await Scalar(cs,
                        "SELECT virtual_value FROM generated_tests.generated_records WHERE id = 100"));
                    var virtualDatabase = new BlueTuskDatabaseModelFactory().Create(
                        cs,
                        new DatabaseModelFactoryOptions([], [Schema]));
                    var virtualColumn = Assert.Single(virtualDatabase.Tables).Columns
                        .Single(column => column.Name == "virtual_value");
                    Assert.False(virtualColumn.IsStored);
                    Assert.Equal("Virtual result", virtualColumn.Comment);
                }
                else
                {
                    var commands = Commands(virtualContext, currentModel, virtualModel);
                    var exception = await Assert.ThrowsAsync<BlueTuskException>(() =>
                        Execute(cs, commands[0].CommandText));
                    Assert.Contains("require PostgreSQL 18 or later", exception.Message,
                        StringComparison.Ordinal);
                }
            }

            using var ordinary = Create<OrdinaryContext>(cs);
            var ordinaryModel = ordinary.GetService<IDesignTimeModel>().Model;
            await Apply(ordinary, currentModel, ordinaryModel, cs);
            Assert.Equal(string.Empty, await Scalar(cs,
                "SELECT attgenerated::text FROM pg_catalog.pg_attribute " +
                "WHERE attrelid = 'generated_tests.generated_records'::regclass " +
                "AND attname = 'stored_value'"));
        }
        finally
        {
            await Cleanup(cs);
        }
    }

    private static void Configure(
        ModelBuilder modelBuilder,
        BlueTuskIdentityGeneration identity,
        string storedExpression,
        bool virtualColumn,
        bool generatedStored,
        bool initialComments)
    {
        var entity = modelBuilder.Entity<GeneratedRecord>();
        entity.ToTable(Table, Schema,
            table => table.HasComment(initialComments ? "Initial table" : "Updated table"));
        entity.HasKey(item => item.Id);
        var id = entity.Property(item => item.Id).HasColumnName("id")
            .UseIdentityColumn(identity);
        if (initialComments)
        {
            id.HasComment("Always identity");
        }

        entity.Property(item => item.BaseValue).HasColumnName("base_value");
        var stored = entity.Property(item => item.StoredValue).HasColumnName("stored_value");
        if (generatedStored)
        {
            stored.HasComputedColumnSql(storedExpression, stored: true);
        }

        if (initialComments)
        {
            stored.HasComment("Stored result");
        }

        if (virtualColumn)
        {
            entity.Property(item => item.VirtualValue).HasColumnName("virtual_value")
                .HasComputedColumnSql("\"base_value\" + 1", stored: false)
                .HasComment("Virtual result");
        }
        else
        {
            entity.Ignore(item => item.VirtualValue);
        }
    }

    private static T Create<T>(string cs) where T : DbContext =>
        (T)Activator.CreateInstance(typeof(T), new DbContextOptionsBuilder<T>().UseBlueTusk(cs).Options)!;

    private static ServiceProvider DesignServices()
    {
        var services = new ServiceCollection();
        services.AddEntityFrameworkDesignTimeServices();
        services.AddEntityFrameworkBlueTusk();
        new BlueTuskDesignTimeServices().ConfigureDesignTimeServices(services);
        return services.BuildServiceProvider();
    }

    private static async Task Apply(DbContext context, IModel? source, IModel target, string cs)
    {
        foreach (var command in Commands(context, source, target))
        {
            await Execute(cs, command.CommandText);
        }
    }

    private static IReadOnlyList<MigrationCommand> Commands(DbContext context, IModel? source, IModel target)
    {
        var operations = context.GetService<IMigrationsModelDiffer>().GetDifferences(
            source?.GetRelationalModel(), target.GetRelationalModel());
        return context.GetService<IMigrationsSqlGenerator>().Generate(operations, target);
    }

    private static async Task Execute(string cs, string sql)
    {
        await using var connection = new BlueTuskConnection(cs);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        _ = await command.ExecuteNonQueryAsync(CancellationToken.None);
    }

    private static async Task<object?> Scalar(string cs, string sql)
    {
        await using var connection = new BlueTuskConnection(cs);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        return await command.ExecuteScalarAsync(CancellationToken.None);
    }

    private static async Task Cleanup(string cs) =>
        await Execute(cs, $"DROP SCHEMA IF EXISTS {Schema} CASCADE");

    private static string ConnectionString()
    {
        var value = Environment.GetEnvironmentVariable("BLUETUSK_TEST_CONNECTION_STRING");
        if (string.IsNullOrWhiteSpace(value))
        {
            throw SkipException.ForSkip("BLUETUSK_TEST_CONNECTION_STRING is not configured.");
        }

        return new BlueTuskConnectionStringBuilder(value)
        {
            SslMode = BlueTuskSslMode.Disable,
            ChannelBinding = BlueTuskChannelBindingMode.Disable,
        }.ConnectionString;
    }

    private sealed class InitialContext(DbContextOptions<InitialContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder) => Configure(
            modelBuilder, BlueTuskIdentityGeneration.Always, "\"base_value\" * 2",
            virtualColumn: false, generatedStored: true, initialComments: true);
    }

    private sealed class ByDefaultContext(DbContextOptions<ByDefaultContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder) => Configure(
            modelBuilder, BlueTuskIdentityGeneration.ByDefault, "\"base_value\" * 2",
            virtualColumn: false, generatedStored: true, initialComments: false);
    }

    private sealed class AlteredStoredContext(DbContextOptions<AlteredStoredContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder) => Configure(
            modelBuilder, BlueTuskIdentityGeneration.ByDefault, "\"base_value\" * 3",
            virtualColumn: false, generatedStored: true, initialComments: false);
    }

    private sealed class VirtualInitialContext(DbContextOptions<VirtualInitialContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder) => Configure(
            modelBuilder, BlueTuskIdentityGeneration.ByDefault, "\"base_value\" * 2",
            virtualColumn: true, generatedStored: true, initialComments: false);
    }

    private sealed class VirtualAlteredContext(DbContextOptions<VirtualAlteredContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder) => Configure(
            modelBuilder, BlueTuskIdentityGeneration.ByDefault, "\"base_value\" * 3",
            virtualColumn: true, generatedStored: true, initialComments: false);
    }

    private sealed class OrdinaryContext(DbContextOptions<OrdinaryContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder) => Configure(
            modelBuilder, BlueTuskIdentityGeneration.ByDefault, "\"base_value\" * 3",
            virtualColumn: false, generatedStored: false, initialComments: false);
    }

    private sealed class GeneratedRecord
    {
        public long Id { get; set; }

        public int BaseValue { get; set; }

        public int StoredValue { get; set; }

        public int VirtualValue { get; set; }
    }
}

#pragma warning restore EF1001
