using Microsoft.EntityFrameworkCore;

namespace BlueTusk.EntityFrameworkCore.Tests;

public sealed class MigrationsTests
{
    private const string ConnectionString =
        "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=bluetusk_tests";

    [Fact]
    public void GenerateCreateScript_produces_PostgreSQL_relational_DDL()
    {
        using var context = CreateContext();

        var sql = context.Database.GenerateCreateScript();

        Assert.Contains("CREATE TABLE \"Parents\"", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE \"Children\"", sql, StringComparison.Ordinal);
        Assert.Contains("CONSTRAINT \"PK_Parents\" PRIMARY KEY", sql, StringComparison.Ordinal);
        Assert.Contains("CONSTRAINT \"FK_Children_Parents_ParentId\" FOREIGN KEY", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE INDEX \"IX_Children_ParentId\"", sql, StringComparison.Ordinal);
        Assert.Contains("character varying(80)", sql, StringComparison.Ordinal);
        Assert.Contains("numeric(12,2)", sql, StringComparison.Ordinal);
        Assert.Contains("DEFAULT 'new'", sql, StringComparison.Ordinal);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql, StringComparison.Ordinal);
    }

    private static MigrationContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<MigrationContext>()
            .UseBlueTusk(ConnectionString)
            .Options;
        return new MigrationContext(options);
    }

    private sealed class MigrationContext(DbContextOptions<MigrationContext> options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var parent = modelBuilder.Entity<Parent>();
            parent.ToTable("Parents");
            parent.Property(entity => entity.Name).HasMaxLength(80);

            var child = modelBuilder.Entity<Child>();
            child.ToTable("Children");
            child.Property(entity => entity.Amount).HasPrecision(12, 2);
            child.Property(entity => entity.Status).HasDefaultValue("new");
        }
    }

    private sealed class Parent
    {
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public List<Child> Children { get; } = [];
    }

    private sealed class Child
    {
        public int Id { get; set; }

        public int ParentId { get; set; }

        public Parent Parent { get; set; } = null!;

        public decimal Amount { get; set; }

        public string Status { get; set; } = string.Empty;
    }
}
