using BlueTusk.Client;
using BlueTusk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Xunit.Sdk;

namespace BlueTusk.EntityFrameworkCore.Tests;

public sealed class RelationalSpecificationTests
{
    private const string OfflineConnectionString =
        "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=bluetusk_tests";

    [Fact]
    public void Relational_services_follow_EF_lifetime_contracts()
    {
        var options = new DbContextOptionsBuilder<SpecificationContext>()
            .UseBlueTusk(OfflineConnectionString)
            .Options;
        using var firstContext = new SpecificationContext(options);
        using var secondContext = new SpecificationContext(options);

        var firstConnection = firstContext.GetService<IRelationalConnection>();
        Assert.Same(firstConnection, firstContext.GetService<IRelationalConnection>());
        Assert.NotSame(firstConnection, secondContext.GetService<IRelationalConnection>());
        Assert.Same(
            firstContext.GetService<IRelationalTypeMappingSource>(),
            secondContext.GetService<IRelationalTypeMappingSource>());
        Assert.NotNull(firstContext.GetService<IRelationalDatabaseCreator>());
        Assert.NotNull(firstContext.GetService<IMigrationsSqlGenerator>());
        Assert.NotNull(firstContext.GetService<IHistoryRepository>());
    }

    [Fact]
    public async Task Relational_query_and_command_behaviors_match_EF_contracts()
    {
        var connectionString = GetConnectionString();
        await ExecuteNonQueryAsync(connectionString, "DROP SCHEMA IF EXISTS ef_spec CASCADE");

        try
        {
            await ExecuteNonQueryAsync(
                connectionString,
                """
                CREATE SCHEMA ef_spec;
                CREATE TABLE ef_spec.parents (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" text NOT NULL,
                    "Category" text NOT NULL,
                    "NullableScore" integer NULL
                );
                CREATE TABLE ef_spec.children (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ParentId" integer NOT NULL REFERENCES ef_spec.parents ("Id") ON DELETE CASCADE,
                    "Note" text NOT NULL
                );
                INSERT INTO ef_spec.parents ("Name", "Category", "NullableScore") VALUES
                    ('Alpha', 'A', 10),
                    ('Beta', 'B', NULL),
                    ('Gamma', 'A', 30);
                INSERT INTO ef_spec.children ("ParentId", "Note") VALUES
                    (1, 'alpha-one'),
                    (1, 'alpha-two'),
                    (3, 'gamma-one');
                """);

            await using var context = CreateContext(connectionString);
            var category = "A";
            var fromSql = await context.Parents
                .FromSqlInterpolated(
                    $"SELECT * FROM ef_spec.parents WHERE \"Category\" = {category}")
                .Where(parent => parent.Name.Contains("ha") || parent.Name.Contains("ma"))
                .OrderBy(parent => parent.Id)
                .AsNoTracking()
                .ToListAsync();
            Assert.Equal(["Alpha", "Gamma"], fromSql.Select(parent => parent.Name));
            Assert.All(fromSql, parent => Assert.Equal(EntityState.Detached, context.Entry(parent).State));

            var graph = await context.Parents
                .Include(parent => parent.Children)
                .AsSplitQuery()
                .AsNoTrackingWithIdentityResolution()
                .OrderBy(parent => parent.Id)
                .ToListAsync();
            Assert.Equal(3, graph.Count);
            Assert.Equal(2, graph[0].Children.Count);
            Assert.All(graph[0].Children, child => Assert.Same(graph[0], child.Parent));

            var updated = await context.Database.ExecuteSqlInterpolatedAsync(
                $"UPDATE ef_spec.parents SET \"NullableScore\" = {20} WHERE \"Name\" = {"Beta"}");
            Assert.Equal(1, updated);

            updated = await context.Children
                .Where(child => child.ParentId == 1)
                .ExecuteUpdateAsync(setters => setters.SetProperty(child => child.Note, "updated"));
            Assert.Equal(2, updated);
            Assert.Equal(2, await context.Children.CountAsync(child => child.Note == "updated"));

            var deleted = await context.Children
                .Where(child => child.ParentId == 3)
                .ExecuteDeleteAsync();
            Assert.Equal(1, deleted);

            var compiledQuery = EF.CompileAsyncQuery(
                (SpecificationContext database, string prefix) => database.Parents
                    .Where(parent => parent.Name.StartsWith(prefix))
                    .Select(parent => parent.Name)
                    .Single());
            Assert.Equal("Gamma", await compiledQuery(context, "G"));
            Assert.Equal(20, await context.Parents.Where(parent => parent.Name == "Beta")
                .Select(parent => parent.NullableScore)
                .SingleAsync());
        }
        finally
        {
            await ExecuteNonQueryAsync(connectionString, "DROP SCHEMA IF EXISTS ef_spec CASCADE");
        }
    }

    private static SpecificationContext CreateContext(string connectionString)
    {
        var options = new DbContextOptionsBuilder<SpecificationContext>()
            .UseBlueTusk(connectionString)
            .Options;
        return new SpecificationContext(options);
    }

    private static async Task ExecuteNonQueryAsync(string connectionString, string sql)
    {
        await using var connection = new BlueTuskConnection(connectionString);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        _ = await command.ExecuteNonQueryAsync(CancellationToken.None);
    }

    private static string GetConnectionString()
    {
        var connectionString = Environment.GetEnvironmentVariable("BLUETUSK_TEST_CONNECTION_STRING");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            throw SkipException.ForSkip("BLUETUSK_TEST_CONNECTION_STRING is not configured.");
        }

        return new BlueTuskConnectionStringBuilder(connectionString)
        {
            SslMode = BlueTuskSslMode.Disable,
            ChannelBinding = BlueTuskChannelBindingMode.Disable,
        }.ConnectionString;
    }

    private sealed class SpecificationContext(DbContextOptions<SpecificationContext> options) : DbContext(options)
    {
        public DbSet<SpecificationParent> Parents => Set<SpecificationParent>();

        public DbSet<SpecificationChild> Children => Set<SpecificationChild>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SpecificationParent>(parent =>
            {
                parent.ToTable("parents", "ef_spec");
                parent.HasKey(entity => entity.Id);
            });
            modelBuilder.Entity<SpecificationChild>(child =>
            {
                child.ToTable("children", "ef_spec");
                child.HasKey(entity => entity.Id);
                child.HasOne(entity => entity.Parent)
                    .WithMany(entity => entity.Children)
                    .HasForeignKey(entity => entity.ParentId);
            });
        }
    }

    private sealed class SpecificationParent
    {
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public string Category { get; set; } = string.Empty;

        public int? NullableScore { get; set; }

        public List<SpecificationChild> Children { get; } = [];
    }

    private sealed class SpecificationChild
    {
        public int Id { get; set; }

        public int ParentId { get; set; }

        public string Note { get; set; } = string.Empty;

        public SpecificationParent Parent { get; set; } = null!;
    }
}
