using System.Data;
using System.Reflection;
using BlueTusk.Client;
using BlueTusk.Data;
using BlueTusk.EntityFrameworkCore.Design.Internal;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Scaffolding;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using Microsoft.Extensions.DependencyInjection;
using Xunit.Sdk;

#pragma warning disable EF1001 // Tests intentionally exercise provider design-time infrastructure.

namespace BlueTusk.EntityFrameworkCore.Tests;

public sealed class ReverseEngineeringTests
{
    [Fact]
    public void Runtime_provider_points_to_design_time_services()
    {
        var attribute = typeof(BlueTuskEntityFrameworkCoreInfo).Assembly
            .GetCustomAttribute<DesignTimeProviderServicesAttribute>();

        Assert.NotNull(attribute);
        Assert.Equal(
            "BlueTusk.EntityFrameworkCore.Design.Internal.BlueTuskDesignTimeServices, BlueTusk.EntityFrameworkCore.Design",
            attribute.TypeName);

        var services = new ServiceCollection();
        new BlueTuskDesignTimeServices().ConfigureDesignTimeServices(services);
        Assert.Contains(services, descriptor => descriptor.ServiceType == typeof(IDatabaseModelFactory));
        Assert.Contains(services, descriptor => descriptor.ServiceType == typeof(IProviderConfigurationCodeGenerator));
        Assert.Contains(services, descriptor => descriptor.ServiceType == typeof(IAnnotationCodeGenerator));
    }

    [Fact]
    public async Task Factory_discovers_core_PostgreSQL_schema_objects()
    {
        var connectionString = GetConnectionString();
        await ExecuteNonQueryAsync(connectionString, "DROP SCHEMA IF EXISTS ef_reverse CASCADE");

        try
        {
            await ExecuteNonQueryAsync(
                connectionString,
                """
                CREATE SCHEMA ef_reverse;
                CREATE SEQUENCE ef_reverse.order_numbers AS bigint START WITH 100 INCREMENT BY 5;
                CREATE TABLE ef_reverse.parents (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    name character varying(80) NOT NULL,
                    code integer NOT NULL,
                    amount numeric(12,2) NOT NULL DEFAULT 1.25,
                    CONSTRAINT pk_reverse_parents PRIMARY KEY (id),
                    CONSTRAINT uq_reverse_parents_code UNIQUE (code)
                );
                COMMENT ON TABLE ef_reverse.parents IS 'Reverse engineering parent';
                COMMENT ON COLUMN ef_reverse.parents.name IS 'Display name';
                CREATE TABLE ef_reverse.children (
                    id integer NOT NULL,
                    parent_id integer NOT NULL,
                    note text,
                    CONSTRAINT pk_reverse_children PRIMARY KEY (id),
                    CONSTRAINT fk_reverse_children_parent FOREIGN KEY (parent_id)
                        REFERENCES ef_reverse.parents (id) ON DELETE CASCADE
                );
                CREATE INDEX ix_reverse_children_parent ON ef_reverse.children USING btree (parent_id);
                CREATE VIEW ef_reverse.parent_names AS
                    SELECT id, name FROM ef_reverse.parents;
                """);

            var factory = new BlueTuskDatabaseModelFactory();
            var model = factory.Create(
                connectionString,
                new DatabaseModelFactoryOptions([], ["ef_reverse"]));

            Assert.Equal("bluetusk_tests", model.DatabaseName);
            Assert.Equal(3, model.Tables.Count);
            var parent = Assert.Single(model.Tables, table => table.Name == "parents");
            var child = Assert.Single(model.Tables, table => table.Name == "children");
            Assert.IsType<DatabaseView>(Assert.Single(model.Tables, table => table.Name == "parent_names"));
            Assert.Equal("Reverse engineering parent", parent.Comment);

            var id = Assert.Single(parent.Columns, column => column.Name == "id");
            var name = Assert.Single(parent.Columns, column => column.Name == "name");
            var amount = Assert.Single(parent.Columns, column => column.Name == "amount");
            Assert.Equal("integer", id.StoreType);
            Assert.Equal(Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.OnAdd, id.ValueGenerated);
            Assert.Equal("character varying(80)", name.StoreType);
            Assert.Equal("Display name", name.Comment);
            Assert.Equal("numeric(12,2)", amount.StoreType);
            Assert.Contains("1.25", amount.DefaultValueSql, StringComparison.Ordinal);

            Assert.Equal("pk_reverse_parents", parent.PrimaryKey?.Name);
            Assert.Equal("id", Assert.Single(parent.PrimaryKey!.Columns).Name);
            Assert.Equal("uq_reverse_parents_code", Assert.Single(parent.UniqueConstraints).Name);
            var foreignKey = Assert.Single(child.ForeignKeys);
            Assert.Equal("fk_reverse_children_parent", foreignKey.Name);
            Assert.Same(parent, foreignKey.PrincipalTable);
            Assert.Equal(ReferentialAction.Cascade, foreignKey.OnDelete);
            var index = Assert.Single(child.Indexes);
            Assert.Equal("ix_reverse_children_parent", index.Name);
            Assert.Equal("btree", index["BlueTusk:IndexMethod"]);

            var sequence = Assert.Single(model.Sequences);
            Assert.Equal("order_numbers", sequence.Name);
            Assert.Equal(100, sequence.StartValue);
            Assert.Equal(5, sequence.IncrementBy);

            var services = new ServiceCollection();
            services.AddEntityFrameworkDesignTimeServices();
            services.AddEntityFrameworkBlueTusk();
            new BlueTuskDesignTimeServices().ConfigureDesignTimeServices(services);
            await using (var serviceProvider = services.BuildServiceProvider())
            {
                var scaffolder = serviceProvider.GetRequiredService<IReverseEngineerScaffolder>();
                var scaffolded = scaffolder.ScaffoldModel(
                    connectionString,
                    new DatabaseModelFactoryOptions([], ["ef_reverse"]),
                    new ModelReverseEngineerOptions(),
                    new ModelCodeGenerationOptions
                    {
                        ContextName = "ReverseContext",
                        ConnectionString = connectionString,
                        ContextNamespace = "ReverseModels",
                        ModelNamespace = "ReverseModels",
                        RootNamespace = "ReverseModels",
                        Language = "C#",
                        ProjectDir = AppContext.BaseDirectory,
                        UseNullableReferenceTypes = true,
                    });
                Assert.Contains("UseBlueTusk", scaffolded.ContextFile.Code, StringComparison.Ordinal);
                Assert.Contains(scaffolded.AdditionalFiles, file => file.Code.Contains("class Parent", StringComparison.Ordinal));
                Assert.Contains(scaffolded.AdditionalFiles, file => file.Code.Contains("class Child", StringComparison.Ordinal));
            }

            await using var openConnection = new BlueTuskConnection(connectionString);
            await openConnection.OpenAsync(CancellationToken.None);
            var filtered = factory.Create(
                openConnection,
                new DatabaseModelFactoryOptions(["ef_reverse.parents"], []));
            Assert.Equal(ConnectionState.Open, openConnection.State);
            Assert.Equal("parents", Assert.Single(filtered.Tables).Name);
            Assert.Empty(filtered.Sequences);

            await using var closedConnection = new BlueTuskConnection(connectionString);
            _ = factory.Create(
                closedConnection,
                new DatabaseModelFactoryOptions(["ef_reverse.parents"], []));
            Assert.Equal(ConnectionState.Closed, closedConnection.State);
        }
        finally
        {
            await ExecuteNonQueryAsync(connectionString, "DROP SCHEMA IF EXISTS ef_reverse CASCADE");
        }
    }

    private static async Task ExecuteNonQueryAsync(string connectionString, string sql)
    {
        await using var connection = new BlueTuskConnection(connectionString);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        _ = await command.ExecuteNonQueryAsync(CancellationToken.None);
    }

    private static string GetConnectionString()
    {
        var connectionString = Environment.GetEnvironmentVariable("BLUETUSK_TEST_CONNECTION_STRING");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            throw SkipException.ForSkip("BLUETUSK_TEST_CONNECTION_STRING is not configured.");
        }

        return new BlueTuskConnectionStringBuilder(connectionString)
        {
            SslMode = BlueTuskSslMode.Disable,
            ChannelBinding = BlueTuskChannelBindingMode.Disable,
        }.ConnectionString;
    }
}

#pragma warning restore EF1001
