<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>Sql</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="..\..\eng\versions\Sql.props" />
  <ItemGroup>
    <Compile Include="..\Shared\ExpansionCapacity\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.Sql\BlueTusk.Sql.csproj" />
    <ProjectReference Include="..\..\src\BlueTusk.Data\BlueTusk.Data.csproj" />
  </ItemGroup>
</Project>
