<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlueTuskProductFamily>ControlPlane</BlueTuskProductFamily>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="..\..\eng\versions\ControlPlane.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlueTusk.ControlPlane.Kubernetes\BlueTusk.ControlPlane.Kubernetes.csproj" />
  </ItemGroup>
</Project>
